### PR TITLE
hide relativenumber

### PR DESCRIPTION
**Pull request by spiderforrest**
relativenumber shows the number column too so

### CODE REVIEW

**Comment by eoh-bse** [comment]
Nice Catch! Thanks for the PR. Will approve and merge :)

**Review by eoh-bse — APPROVED** [review]

**Comment by spiderforrest** [comment]
@eoh-bse Too lazy to open another pr but `vim.opt.fillchars = { eob = " " }` gets rid of the ~ on each newline-I think your personal config does something to supress that, but mine doesn't so I had to add that for maximum cleanness.

**Comment by spiderforrest** [comment]
Wait, `opt_local` like the rest

**Comment by eoh-bse** [comment]
Thanks for pointing it out. I will look into this.
Next time, please create an issue under `Issues` tab.
Thanks!

**Pull request merged**
